import styles from "../../styles/Home.module.css";
import App from "../../components/App";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

//import Custom Style scss
export default function Home() {

  const title = useSelector((state) => state.currentAuth.title);

  return (
    <div className={styles.container}>

      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <main>
        <App />
      </main>

      <footer className={styles.footer}>
        Powered by <span className={styles.logo}></span>
      </footer>
    </div>
  );
}
