import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import App from "../components/App";

//import Custom Style scss
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>800 millions</title>
        <div id="mapp"></div>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <App />
      </main>

      <footer className={styles.footer}>
        Powered by <span className={styles.logo}></span>
      </footer>
    </div>
  );
}
